export const apiKey = "aec871cfe8beffd2db6a64074c0ac7ed";
export const TrendingMoviesImages = [
  require("../Images/avatar.png"),
  require("../Images/back.png"),
  require("../Images/cardio.png"),
  require("../Images/chest.png"),
  require("../Images/lowerArms.png"),
  require("../Images/lowerLegs.png"),
  require("../Images/neck.png"),
  require("../Images/shoulders.png"),
  require("../Images/upperArms.png"),
  require("../Images/upperLegs.png"),
  require("../Images/waist.png"),
  require("../Images/welcome.png"),
];
export const UpcomingImages = [
  require("../Images/avatar.png"),
  require("../Images/back.png"),
  require("../Images/cardio.png"),
  require("../Images/chest.png"),
  require("../Images/lowerArms.png"),
  require("../Images/lowerLegs.png"),
  require("../Images/neck.png"),
  require("../Images/shoulders.png"),
  require("../Images/upperArms.png"),
  require("../Images/upperLegs.png"),
  require("../Images/waist.png"),
  require("../Images/welcome.png"),
];
export const TopRatedImages = [
  require("../Images/avatar.png"),
  require("../Images/back.png"),
  require("../Images/cardio.png"),
  require("../Images/chest.png"),
  require("../Images/lowerArms.png"),
  require("../Images/lowerLegs.png"),
  require("../Images/neck.png"),
  require("../Images/shoulders.png"),
  require("../Images/upperArms.png"),
  require("../Images/upperLegs.png"),
  require("../Images/waist.png"),
  require("../Images/welcome.png"),
];
